import type { VersionIngredient, VersionStep } from "@/types/database";

// Sample recipe data for new users - allows them to test AI chat immediately
export const SAMPLE_RECIPE = {
  // Master recipe fields
  title: "Garlic Butter Shrimp Pasta",
  description: "Quick 15-minute dinner with restaurant-quality flavor",
  mode: "cooking" as const,
  cuisine: "Italian",
  category: "Main Course",

  // Version fields
  prep_time_minutes: 5,
  cook_time_minutes: 10,
  servings: 2,
  servings_unit: "servings",
  difficulty_score: 2, // Easy

  ingredients: [
    {
      id: "sample-ing-1",
      item: "spaghetti",
      quantity: 8,
      unit: "oz",
      preparation: null,
      is_optional: false,
      sort_order: 1,
      original_text: "8 oz spaghetti",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Pasta & Grains",
    },
    {
      id: "sample-ing-2",
      item: "large shrimp",
      quantity: 1,
      unit: "lb",
      preparation: "peeled and deveined",
      is_optional: false,
      sort_order: 2,
      original_text: "1 lb large shrimp, peeled & deveined",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Seafood",
    },
    {
      id: "sample-ing-3",
      item: "butter",
      quantity: 4,
      unit: "tbsp",
      preparation: null,
      is_optional: false,
      sort_order: 3,
      original_text: "4 tbsp butter",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Dairy",
    },
    {
      id: "sample-ing-4",
      item: "garlic",
      quantity: 4,
      unit: "cloves",
      preparation: "minced",
      is_optional: false,
      sort_order: 4,
      original_text: "4 cloves garlic, minced",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Produce",
    },
    {
      id: "sample-ing-5",
      item: "lemon",
      quantity: 1,
      unit: null,
      preparation: "juiced",
      is_optional: false,
      sort_order: 5,
      original_text: "1 lemon, juiced",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Produce",
    },
    {
      id: "sample-ing-6",
      item: "fresh parsley",
      quantity: 0.25,
      unit: "cup",
      preparation: "chopped",
      is_optional: true,
      sort_order: 6,
      original_text: "1/4 cup fresh parsley, chopped",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Produce",
    },
    {
      id: "sample-ing-7",
      item: "red pepper flakes",
      quantity: 0.25,
      unit: "tsp",
      preparation: null,
      is_optional: true,
      sort_order: 7,
      original_text: "1/4 tsp red pepper flakes",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Spices",
    },
    {
      id: "sample-ing-8",
      item: "salt and pepper",
      quantity: null,
      unit: null,
      preparation: "to taste",
      is_optional: false,
      sort_order: 8,
      original_text: "Salt and pepper to taste",
      confidence_status: "verified",
      user_verified: true,
      grocery_category: "Spices",
    },
  ] as VersionIngredient[],

  steps: [
    {
      id: "sample-step-1",
      step_number: 1,
      instruction:
        "Bring a large pot of salted water to boil. Cook spaghetti according to package directions until al dente. Reserve 1/2 cup pasta water before draining.",
      duration_minutes: 10,
      temperature_value: null,
      temperature_unit: null,
      equipment: ["large pot", "colander"],
      techniques: ["boiling"],
      timer_label: "Pasta cooking",
    },
    {
      id: "sample-step-2",
      step_number: 2,
      instruction:
        "While pasta cooks, pat shrimp dry with paper towels and season with salt and pepper.",
      duration_minutes: 2,
      temperature_value: null,
      temperature_unit: null,
      equipment: ["paper towels"],
      techniques: ["seasoning"],
    },
    {
      id: "sample-step-3",
      step_number: 3,
      instruction:
        "Melt 2 tablespoons butter in a large skillet over medium-high heat. Add shrimp in a single layer and cook 2-3 minutes per side until pink and opaque. Remove from pan and set aside.",
      duration_minutes: 5,
      temperature_value: null,
      temperature_unit: null,
      equipment: ["large skillet", "spatula"],
      techniques: ["sauteing"],
      timer_label: "Shrimp cooking",
    },
    {
      id: "sample-step-4",
      step_number: 4,
      instruction:
        "Add remaining 2 tablespoons butter to the same pan. Add minced garlic and red pepper flakes (if using). Cook for 30 seconds until fragrant - don't let it brown!",
      duration_minutes: 1,
      temperature_value: null,
      temperature_unit: null,
      equipment: ["large skillet"],
      techniques: ["sauteing"],
    },
    {
      id: "sample-step-5",
      step_number: 5,
      instruction:
        "Return shrimp to the pan. Add drained pasta, lemon juice, and 1/4 cup of the reserved pasta water. Toss everything together, adding more pasta water if needed to create a light sauce.",
      duration_minutes: 2,
      temperature_value: null,
      temperature_unit: null,
      equipment: ["large skillet", "tongs"],
      techniques: ["tossing"],
    },
    {
      id: "sample-step-6",
      step_number: 6,
      instruction:
        "Remove from heat. Taste and adjust seasoning with salt and pepper. Garnish with fresh parsley and serve immediately.",
      duration_minutes: 1,
      temperature_value: null,
      temperature_unit: null,
      equipment: [],
      techniques: ["plating"],
    },
  ] as VersionStep[],

  // Metadata
  is_sample: true,
  tags: ["quick", "seafood", "pasta", "date-night", "weeknight"],
};

export const SAMPLE_RECIPE_TITLE = SAMPLE_RECIPE.title;
